manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    # - name: nickconway
    #   url-base: https://github.com/nickconway
  projects:
    - name: zmk
      # remote: zmkfirmware
      # revision: main
      remote: petejohanson
      revision: stephen/split-encoder
      import: app/west.yml
      # remote: nickconway
      # revision: dynamic-macro
      # import: app/west.yml
  self:
    path: config
    
